name: Native Image

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build_non_win_images:
    name: 'Build Native Image ${{ matrix.platform }}'
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
          - os: 'macos-latest'
            platform: 'darwin-amd64'
          - os: 'windows-latest'
            platform: 'win-amd64'
    runs-on: ${{matrix.os}}
    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache/restore@v3
        with:
          path: |
            build/libs
          key: "libs-${{ github.run_id }}"
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Generate GraalVM configuration
        run: |
          mkdir -p native-image-config-dir
          printf '+--+--------+
          |  |        |
          |  |        |
          |  |    /---+
          |  |    |   |
          |  |    |   |
          +--+----+---/' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/ditaamini-${{ inputs.release-version }}.jar" --svg -
          printf '+--+--------+
          |  |        |
          |  |        |
          |  |    /---+
          |  |    |   |
          |  |    |   |
          +--+----+---/' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/ditaamini-${{ inputs.release-version }}.jar" -

      - name: Generate native image
        run: |
          native-image -H:ConfigurationFileDirectories=native-image-config-dir --no-fallback --report-unsupported-elements-at-runtime -jar "build/libs/ditaamini-${{ inputs.release-version }}.jar" -H:Path="build/libs" -H:Name="ditaamini-${{ matrix.platform }}-${{ inputs.release-version }}"

      - name: Cache native image
        uses: actions/cache/save@v3
        with:
          path: "build/libs/ditaamini-${{ matrix.platform }}-*"
          key: "native-image-${{ matrix.platform }}-${{ github.run_id }}"
          enableCrossOsArchive: true